syntax = "proto3";

package org.example.mappro.tiles.grpc;

import "google/protobuf/empty.proto";

option java_package = "org.example.mappro.tiles.grpc";
option java_multiple_files = true;

service TileService {
    rpc GetTile (TileRequest) returns (stream ChunkResponse);
    rpc HealthCheck (google.protobuf.Empty) returns (HealthResponse);
}

message TileRequest {
    int32 z = 1;
    int32 x = 2;
    int32 y = 3;
    repeated string types = 4;
    repeated string severities = 5;
    string from_date = 6;
    bool show_cities = 7;
    string lang = 8;
}

message ChunkResponse {
    bytes data = 1;
    bool is_last = 2;
}

message HealthResponse {
    string status = 1;
    string version = 2;
    int64 uptime_seconds = 3;
}