spring.application.name=map-pro

spring.datasource.url=jdbc:postgresql://localhost:5432/map_pro
spring.datasource.username=postgres
spring.datasource.password=123456789

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MVC
spring.mvc.static-path-pattern=/static/**

# Web resources
spring.web.resources.static-locations=file:/tmp/data/images/

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

jwt.secret=R9u2eUoP3aJv7bYzT1xLkNhMqWeYtGhZ0pAsDfGvHtMnBcXq

# ===================== JWT CONFIG =====================
jwt.access-secret=someverylongsecretkeyforaccessjwt1234567890
jwt.refresh-secret=anotherverylongsecretkeyforrefreshjwt1234567890
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

spring.devtools.restart.enabled=false
spring.output.ansi.enabled=always